apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jotp9otfa-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jotp9otfa-go 
  name: jotp9otfa-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jotp9otfa-go 
